# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ostickett1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_53bbb17669d9425891447908e74dab86 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_18b47ddde5fe48aab1656b6855ee0a02 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_53bbb17669d9425891447908e74dab86 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ostickett1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_55dd33ace0c443179f86f5783230553c }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_53bbb17669d9425891447908e74dab86 }}/appsvc/staticsite:${{ github.sha }}'